### ISSUE TITLE
Reading HDF5 data in python

### ISSUE THREAD

**Issue by nkupelioglu** [mgaoling/mpl_dataset_toolbox#1]
**Brief description of the problem:** Loading the hdf5 files (event camera data in sequences) with the h5py package in Python does not work directly. This is a problem I have never encountered with any publicly available event dataset.
The following snippet should have the expected behavior of loading the data.
```
import h5py
dset = h5py.File(name="../sequences/sofa_fast/sofa_fast_right_event.hdf5", mode='r')
print(dset.get('events/x')[:10])
dset.close()
```
However, it throws the following error:

```
OSError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
```

**Solution/Workaround:** Installing `hdf5plugin` package through pip.
```
pip install hdf5plugin
```  
and even if it is unused importing it.

```
import hdf5plugin
import h5py

dset = h5py.File(name="../sequences/sofa_fast/sofa_fast_right_event.hdf5", mode='r')
print(dset.get('events/x')[:10])
dset.close()
```

This results in the correct behavior.

```
[376 414 386 633 249 392  56 467 262 164]
```

**Comment by mgaoling** [comment]
Thank you for sharing, and `hdf5plugin` is a required module for loading.

We follow the same data format as the [DSEC dataset](https://dsec.ifi.uzh.ch/data-format/), in which the event data are stored in hdf5 files under zstd compression mode.
