### ISSUE TITLE
Error when Compiling

### ISSUE THREAD

**Issue by msh003** [mgaoling/mpl_dataset_toolbox#10]
Hello,
Thank you for sharing this useful toolbox. I have a problrm during the installation
when I run 
`catkin_make`
I face this error nd it is not compilewd.

> /home/msh/catkin_ws/src/mpl_dataset_toolbox/include/utility.hpp:6:10: fatal error: mpl_dataset_toolbox/Event.h: No such file or directory
 #include <mpl_dataset_toolbox/Event.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

> 

I would apprecite you please help me.

**Comment by mgaoling** [comment]
Try the following code:
`catkin_make clean`
`catkin_make -j1`

**Comment by msh003** [comment]
Thank you so much
It works

**Comment by jiheddachraoui** [comment]
@mgaoling hello i did that but i'm facing the same error
