### ISSUE TITLE
关于单目惯性vio初始化

### ISSUE THREAD

**Issue by xiaozhang-lang** [mgaoling/mpl_dataset_toolbox#13]
作者您好，感谢您开源的公共数据集。
但是我现在遇到了一个问题无法解决：在Vins-Mono中，imu的配置参数如何给定才能保证初始化成功呢？无论我如何调试初始化总是失败，进而导致建图失败。可是我在论文中看到的效果还是不错的。
此外，Vins-Fusion双目vio效果还是可以的。
作为一个初学者，希望能得到一些有用的建议。
非常感谢！

如下面所示：

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.04          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004       # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.00002      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 8.6897751     # gravity magnitude

**Comment by mgaoling** [comment]
可以参考一下我们当时运行VINS代码的参数。

[VINS-mono.zip](https://github.com/mgaoling/mpl_dataset_toolbox/files/13915296/VINS-mono.zip)
[VINS-fusion.zip](https://github.com/mgaoling/mpl_dataset_toolbox/files/13915302/VINS-fusion.zip)

**Comment by xiaozhang-lang** [comment]
您好，请问你们当时运行Vins-Mono的时候是添加的双目相机的左目和Imu吗？为什么我直接用的你们的参数，还是出现飘飞的情况？

**Comment by mgaoling** [comment]
可以对参数作适当放缩，以适配VINS的系统。

**Comment by xiaozhang-lang** [comment]
非常感谢您的及时回复，通过适当调整对我帮助很大。
然而我对比了您给我的双目和单目的参数，我发现在vins-mono中yaml文件话题订阅的是left camera，但是下面的相机内参却是双目相机中的right camera，请问在bag文件中的相机话题是left camera还是right camera呢？
希望得到您的回复
![image](https://github.com/mgaoling/mpl_dataset_toolbox/assets/48277959/1836a00c-ff80-4008-9bdd-07fe07021530)

**Comment by mgaoling** [comment]
不是特别记得了。两台RGB相机在内参上相差不大，可以都做测试。

**Comment by xiaozhang-lang** [comment]
> 不是特别记得了。两台RGB相机在内参上相差不大，可以都做测试。

非常感谢，目前已经调试成功了。解决了当前的问题。

**Comment by xiaozhang-lang** [comment]
作者您好，我在使用imu.txt中的地磁信息数据的时候发现地磁信息在硬件中是以四元数的形式定义的。
如果我想得到每个时间戳下的地磁场强度，请问该如何计算呢？qw这一分量是否参与地磁向量呢？
