### ISSUE TITLE
Request for Accessible Download Link within the Chinese mainland

### ISSUE THREAD

**Issue by DapengFeng** [mgaoling/mpl_dataset_toolbox#15]
Dear Ling Gao,

I hope this message finds you well. I am currently encountering difficulties downloading substantial files from Google Drive, even with the use of a VPN. The file sizes are quite large, making the process cumbersome and inefficient.

Would it be possible for you to provide an alternative download link that is accessible within the Chinese mainland? Your assistance in this matter would be greatly appreciated as it would significantly facilitate my research work.

Thank you very much for considering my request. I look forward to your prompt response.

Best regards,
Dapeng Feng

**Comment by mgaoling** [comment]
Thanks for your interest.

Unfortunately, I cannot do so; it's too much work.
