### ISSUE TITLE
The color images of the RGB-D sensor (kinect)

### ISSUE THREAD

**Issue by Unsigned-Long** [mgaoling/mpl_dataset_toolbox#16]
Thank you for your dataset :+1: ! However, I am curious about the RGB-D dataset. For the Kinect camera, it seems that you only released the data from the topic `/kinect/depth_image`, but not the data from the topic `/kinect/color_image`. Is that right? If there is anything I have overlooked, please guide me. Thank you!

**Comment by mgaoling** [comment]
Only depth information from the Kinect sensor is recorded.

If you need to reproject this depth data onto a different camera frame, you can refer to the [k4a_projector](https://github.com/greatoyster/k4a_projector) repository for guidance.

**Comment by Unsigned-Long** [comment]
Thank you for your prompt reply and instructions. My question has been clearly answered and this issue will be closed.
