### ISSUE TITLE
Invalid Values in Depth Image Corners Resulting in Hexagonal Display

### ISSUE THREAD

**Issue by Rainlv** [mgaoling/mpl_dataset_toolbox#17]
## Description:

In the dataset, the corners of the depth images have pixel values of 0, leading to a hexagonal appearance for the entire image. This issue is consistent across all depth images in the dataset.

## Questions:

1. Why do the corners have invalid values?
2. Are there any solutions or recommendations to handle these invalid values?

Here's an example image which is processed by the scipt:
```python
import cv2

img = cv2.imread(
    "DEPTH_IMGE_PATH",
    cv2.IMREAD_UNCHANGED)

img = img.astype("float32")
img = img / 1000.

img = (img - img.min()) / (img.max() - img.min())
img = img * 255
img = img.astype("int8")
cv2.imwrite("img.png", img)

```
![img_screenshot_29 08 2024](https://github.com/user-attachments/assets/b77896ac-ffaf-45a6-8722-eaa7b6bdc3e6)

**Comment by greatoyster** [comment]
This is because the Azure Kinect we are using has its own FoV in this shape. You can refer to this webpage: https://learn.microsoft.com/en-us/previous-versions/azure/kinect-dk/depth-camera.
