### ISSUE TITLE
Is there any way to get the camera intrinsics after reprojected by k4a_projector?

### ISSUE THREAD

**Issue by Rainlv** [mgaoling/mpl_dataset_toolbox#18]
Hello, after reprojecting depth image to other camera frame, the image size has been changed obviously. So if i only use the images that have been aligned and reprojected, how can I get the new  camera intrinsics. And by the way, will the extrinsic be changed?

**Comment by mgaoling** [comment]
Hi.

The image size has NOT been changed. Therefore, there is no need to update the intrinsic or the extrinsic.

You can refer to [this issue](https://github.com/mgaoling/mpl_calibration_toolbox/issues/1) for better understanding.

**Comment by Rainlv** [comment]
Thank for your promt reply. 

Well, take `hdr_normal1` as an example. The depth images from raw bag are sized as 640 * 576 while the same frame reprojected to left camera is 1224 * 1024 which is the same as left regular camera actually. Does this have no effect with intrinsic?

And the intrinsic from `rgbd_depth_camera_factory_intrinsic_results` is 1024 *1024, which do not match either. So is there anything I overlooked?

The depth image from the raw bag:
![image](https://github.com/user-attachments/assets/81fd5a30-77fa-4448-bb9a-70f2ee023ed1)

The depth image from the reprojected bag (left_camera_depth topic):
![image](https://github.com/user-attachments/assets/65d25121-a131-41de-b15c-78351b04effa)

**Comment by mgaoling** [comment]
I think you need to double-check the [input yaml file](https://github.com/greatoyster/k4a_projector/blob/main/config/config.yaml). If I remember correctly, this will return depth images with the same resolution as your target camera.

**Comment by Rainlv** [comment]
So you mean that we can take the `target_rosbag`'s camera intrinsic as the reprojected camera intrinsic?  In the [input yaml file](https://github.com/greatoyster/k4a_projector/blob/main/config/config.yaml), the reprojected left camera depth image' intrinsic is the same with the image in `target_rosbag` like `left_camera`?

**Comment by greatoyster** [comment]
Yes.

**Comment by Rainlv** [comment]
> Yes.

Thanks!

**Comment by Chensiyu00** [comment]
Hi Rainlv, @Rainlv 

When I use the k4aprojector to project the depth, I face with this error.

terminate called after throwing an instance of 'YAML::TypedBadConversion<std::vector<double, std::allocator > >' what(): yaml-cpp: error at line 0, column 0: bad conversion

The problem seems that the code need read "transformation_to_kinect_color" keywords in the code. But it is missing in the calib file. I use this calib file:
https://star-datasets.github.io/vector/assets/yaml/left_regular_camera_intrinsic_results.yaml

Do you meet with this prblem? What should I do? 

Thanks.

**Comment by Rainlv** [comment]
> Hi Rainlv, @Rainlv
> 
> When I use the k4aprojector to project the depth, I face with this error.
> 
> terminate called after throwing an instance of 'YAML::TypedBadConversion<std::vector<double, std::allocator > >' what(): yaml-cpp: error at line 0, column 0: bad conversion
> 
> The problem seems that the code need read "transformation_to_kinect_color" keywords in the code. But it is missing in the calib file. I use this calib file: https://star-datasets.github.io/vector/assets/yaml/left_regular_camera_intrinsic_results.yaml
> 
> Do you meet with this prblem? What should I do?
> 
> Thanks.

Hello!
I just use the calib file provided in this repo's data dir which containes `transformation_to_kinect_color` keywords. Maybe you can take the [file](https://github.com/greatoyster/k4a_projector/blob/main/data/right_regular_camera_intrinsic_results.yaml) as a look. I think you may use the calib file from the dataset page which miss `transformation_to_kinect_color` keyword.

**Comment by Chensiyu00** [comment]
Hi Rainlv, @Rainlv 

Very Thanks for your help. I indeed use the dataset page. It really help me. And I have another question, do the output depth need a depth scale correction to get the real depth? For example, in TUM RGBD dataset,  to get the real depth, I need to do (depth_png / depth_scale) to get the real depth. 

Thank you.

**Comment by Rainlv** [comment]
> Hi Rainlv, @Rainlv
> 
> Very Thanks for your help. I indeed use the dataset page. It really help me. And I have another question, do the output depth need a depth scale correction to get the real depth? For example, in TUM RGBD dataset, to get the real depth, I need to do (depth_png / depth_scale) to get the real depth.
> 
> Thank you.

Hello! 
The unit of the depth map should be in millimeters. If you want to convert it to meters, depth_scale should be set to 1000.

**Comment by Chensiyu00** [comment]
Hi Rainlv, 

My problems are solved. Very Thanks for your help.

**Comment by Chensiyu00** [comment]
Hi Rainlv, @Rainlv 

I meet a new problem. When I run roslaunch k4a_projector run.launch.

ERROR: Invalid file path: /root/catkin_ws/src/k4a_projector/data/sofa_normal1.synced.left_camera.bag

But  this path "/root/catkin_ws/src/k4a_projector/data/" exists?

Do you know how to solve the problem?

Thank you.

**Comment by Rainlv** [comment]
> Hi Rainlv, @Rainlv
> 
> I meet a new problem. When I run roslaunch k4a_projector run.launch.
> 
> ERROR: Invalid file path: /root/catkin_ws/src/k4a_projector/data/sofa_normal1.synced.left_camera.bag
> 
> But this path "/root/catkin_ws/src/k4a_projector/data/" exists?
> 
> Do you know how to solve the problem?
> 
> Thank you.

Check the [config](https://github.com/greatoyster/k4a_projector/blob/main/config/config.yaml) file is correct, do not use the absolute path like `/root/catkin_ws/src/k4a_projector/data/xxxxx`, just use `/data/xxx` and the path will be resovled as `/root/catkin_ws/src/k4a_projector/data/xxxx`. 

So what you should do is put the bag files into   `/root/catkin_ws/src/k4a_projector/data` dir, take `sofa_normal1.synced.left_camera.bag` as an example , copy it to `/root/catkin_ws/src/k4a_projector/data/sofa_normal1.synced.left_camera.bag` and set the config item to `/data/sofa_normal1.synced.left_camera.bag`

**Comment by Chensiyu00** [comment]
Hi Rainlv,

It works. Very thanks for your help.

**Comment by Chensiyu00** [comment]
Hi Rainlv, @Rainlv 

I have a question about the intrinics. Do you directly use the intrinsics giving in the [file](https://github.com/greatoyster/k4a_projector/blob/main/data/left_regular_camera_intrinsic_results.yaml), i.e. 

[ 886.19107,    0.     ,  610.57891,
   0.     ,  886.59163,  514.59271,
   0.     ,    0.     ,    1.     ]

 Have you succeeded to use the intrinsics to achieve expected results?

From my understanding, in the [code](https://github.com/greatoyster/k4a_projector/blob/main/include/CameraCalibration.hpp), the optimized intrinsic is used.

**Comment by Rainlv** [comment]
> Hi Rainlv, @Rainlv
> 
> I have a question about the intrinics. Do you directly use the intrinsics giving in the [file](https://github.com/greatoyster/k4a_projector/blob/main/data/left_regular_camera_intrinsic_results.yaml), i.e.
> 
> [ 886.19107, 0. , 610.57891, 0. , 886.59163, 514.59271, 0. , 0. , 1. ]
> 
> Have you succeeded to use the intrinsics to achieve expected results?
> 
> From my understanding, in the [code](https://github.com/greatoyster/k4a_projector/blob/main/include/CameraCalibration.hpp), the optimized intrinsic is used.

yes

**Comment by Chensiyu00** [comment]
> > Hi Rainlv, @Rainlv
> > I have a question about the intrinics. Do you directly use the intrinsics giving in the [file](https://github.com/greatoyster/k4a_projector/blob/main/data/left_regular_camera_intrinsic_results.yaml), i.e.
> > [ 886.19107, 0. , 610.57891, 0. , 886.59163, 514.59271, 0. , 0. , 1. ]
> > Have you succeeded to use the intrinsics to achieve expected results?
> > From my understanding, in the [code](https://github.com/greatoyster/k4a_projector/blob/main/include/CameraCalibration.hpp), the optimized intrinsic is used.
> 
> yes

OK. Thanks for your help
