### ISSUE TITLE
VECtor Benchmark数据集使用及引用请求

### ISSUE THREAD

**Issue by Unsigned-Long** [mgaoling/mpl_dataset_toolbox#20]
你好，感谢你们开源的VECtor Benchmark数据集！我想在论文使用你们的数据集，并想在论文里放置如下的传感器套件和场景图，不知可否？期待你们的回复，感谢！ :smiley:  对应的论文已经上传到arVix，具体的图片使用和数据集应用和引用细节可以从这边的链接访问：
+ arXiv链接：https://arxiv.org/abs/2409.07116
+ 论文标题：iKalibr-RGBD: Partially-Specialized Target-Free Visual-Inertial Spatiotemporal Calibration For RGBDs via Continuous-Time Velocity Estimation

![image](https://github.com/user-attachments/assets/cba07d0c-d894-4a28-b2b6-7d616059f43f)

**Comment by mgaoling** [comment]
没问题。

**Comment by Unsigned-Long** [comment]
谢谢你！
