### ISSUE TITLE
Time Misalignment of Event Streams in bag2hdf5.py

### ISSUE THREAD

**Issue by jiheddachraoui** [mgaoling/mpl_dataset_toolbox#21]
Hello, in the bag2hdf5.py script, I've noticed that in some cases the offset is incorrectly calculated, causing all the event streams to be delayed. For example, in the HDF5 file, the first event starts after 4 seconds instead of being normalized to 0. However, in other cases, it works correctly. Does msg.events[0] truly refer to the first event chronologically?
Thanks!!

**Comment by mgaoling** [comment]
I don't quite get your question. Where the "4 seconds" comes from?

You may want to refer to [this webpage](https://star-datasets.github.io/vector/about/synchronization/) or check [this repository](https://github.com/sjtuyuxuan/sync_toolbox) for better understanding.

**Comment by jiheddachraoui** [comment]
The delay (4s) varies randomly between bags, with some cases being more pronounced. The issue arises when the HDF5 file starts with a delay on the slave camera in a master-slave setup. In these cases, the first event on the slave camera appears several seconds after t=0 instead of starting as expected. However, in all other bags with the same configuration, it works correctly without any delays.

**Comment by jiheddachraoui** [comment]
Hello, I checked these bags, and it turns out the issue is with the bag itself, not your code. Thank you!
