### ISSUE TITLE
关于units_scooter1.synced.imu.txt惯导数据文件中地磁数据的问题

### ISSUE THREAD

**Issue by xiaozhang-lang** [mgaoling/mpl_dataset_toolbox#22]
作者您好，
         感谢您的开源数据集。我在实验过程中发现，VECtor给到的任何imu.txt中magnetometer数据总是以四元数的形式存在的，请问这是直接从硬件中读取的原始数据吗？
         如果我想获得这个点的磁场强度，该如何转换或者操作呢？我查看了IMU的官网手册和论坛，没有找到明确的方法。
         谢谢，期待您的指点。
下面是文件内容：
# IMU data for board_slow1.synced
# Readings from gyroscope[rad/s], accelerometer[m/s^2], and magnetometer[quaternion]
# timestamp gx gy gz ax ay az qx qy qz qw
1642521684.836608 -0.00578761 -0.0122532 0.00390559 -10.0224 -0.299869 -0.820489 -0.166982 0.716317 0.14391 0.66204

**Comment by mgaoling** [comment]
你好，我也不是特别清楚计算磁场强度的方法。我们仅录制了上述读数。

**Comment by xiaozhang-lang** [comment]
> 你好，我也不是特别清楚计算磁场强度的方法。我们仅录制了上述读数。

请问方便提供一下设备的SDK或者帮助文档吗？我自己查看一下，感谢您的及时答复！谢谢

**Comment by mgaoling** [comment]
你可以查阅一下这个网站，不太确定当时是否用的是这个。

https://wiki.ros.org/xsens_driver

**Comment by xiaozhang-lang** [comment]
好吧，我好像还是没有找到，您给提供的是集成到ROS中的话题信息，至于为什么是输出四元数形式，好像没有说明，我对磁力计理解的也不是很清楚。
我目前参考的是忽略四元数中的qw这一项，应该也是可以的。
   感谢您的回复！
