### ISSUE TITLE
How to get the event within the exposure time of the image

### ISSUE THREAD

**Issue by Chensiyu00** [mgaoling/mpl_dataset_toolbox#23]
Dear Gao Ling, @mgaoling 

Thanks for your great dataset. It really help me.

Current I need to get the event within the exposure time of each image. I use the timestamp.txt in the left_image.zip in this [page](https://star-datasets.github.io/vector/download/). Based on the exposure start time and exposure end time, I select the event within this time. But I face with this proble
m, the depth is not align with the event, like this issue https://github.com/mgaoling/mpl_calibration_toolbox/issues/1.
The depth of the event camera is got by the k4a_projector.

![1642650001 532984](https://github.com/user-attachments/assets/4422f0a6-e987-4a95-b4c7-d6bb9457eddf)

Is it the correct way to get the event within the exposure time of each image?
How can I get the aligned event with the depth (including time)? Could you give somewhat detailed methods?

Thanks very much

**Comment by mgaoling** [comment]
As stated in https://github.com/mgaoling/mpl_calibration_toolbox/issues/1, we believe that some of the misalignment may stem from Kinect hardware issue. By following the guidelines in the k4a_projector project, and ensuring that all the parameters and inputs are correctly configured, you should be able to achieve better results.

Additionally, I recommend checking out our group's [latest contribution](https://arxiv.org/abs/2401.08043) for further insights. Thanks.

**Comment by Chensiyu00** [comment]
OK. Very Thanks for your help.

Is it the correct way to get the event within the exposure time of each image, based on my desciption?

**Comment by mgaoling** [comment]
That could be an option.

**Comment by Chensiyu00** [comment]
Ok. Thanks very much.

**Comment by Chensiyu00** [comment]
Dear Gao ling,
