### ISSUE TITLE
Reference frame for gt poses

### ISSUE THREAD

**Issue by ghoshsuman** [mgaoling/mpl_dataset_toolbox#3]
Hi, 

In the webpage for groundtruth, it is written "Note that the ground truth is given by applying the [hand-eye calibration result](https://star-datasets.github.io/vector/calibration) to the MoCap readings."
So, I wanted to confirm in which reference frame are the gt poses provided? In the mocap body frame, or the regular left camera (cam0) frame?

For the large-scale sequences as well, which reference frame is the gt poses reported in? LiDAR?

Thanks for your help!

**Comment by mgaoling** [comment]
Hi Suman,

The ground truth poses for the small-scale data sequences are raw MoCap readings (i.e. marker position and orientation in the mocap body frame), hence further applying the hand-eye calibration is needed if you want to transform into the left camera frame.

For large-scale data sequences, ground truth poses are indeed under the LiDAR frame.

The wording in the description seems ambiguous, and I will modify it later. Thanks for pointing this out!

Ling.
