### ISSUE TITLE
Wrong hdf5 compression listed in the docs

### ISSUE THREAD

**Issue by klowrey** [mgaoling/mpl_dataset_toolbox#4]
The website documentation notes that the hdf5 files are compressed with bzip2, but actually looking at the files:

h5dump -pH corner_slow1.synced.left_event.hdf5 | grep 'FILTER\|COMMENT'
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32015
               COMMENT Zstandard compression: http://www.zstd.net
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32015
               COMMENT Zstandard compression: http://www.zstd.net
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32015
               COMMENT Zstandard compression: http://www.zstd.net
         FILTERS {
            USER_DEFINED_FILTER {
               FILTER_ID 32015
               COMMENT Zstandard compression: http://www.zstd.net
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32015
            COMMENT Zstandard compression: http://www.zstd.net
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32015
            COMMENT Zstandard compression: http://www.zstd.net

You can see that Zstd compression is used instead. Admittedly I only looked at this one file, but this inconsistency can affect those using their own tooling to decompress the data.

Thanks

**Comment by greatoyster** [comment]
Thanks for your reminding, after our double check, we finally comfirmed that we used Zstd (see scripts/bag2hdf5.py) in hdf5 compression. The official docs will be updated soon.
