### ISSUE TITLE
Acquisition of LiDAR data

### ISSUE THREAD

**Issue by xhlinxm** [mgaoling/mpl_dataset_toolbox#5]
The download link of LiDAR data cannot be found on the download page【https://star-datasets.github.io/vector/download/】 of the dataset. Will point cloud data be provided in the future?

**Comment by mgaoling** [comment]
Sorry, I don't get your question. LiDAR data sequences are provided on the download page.

If referring to small-scale data sequences, an RGB-D camera offers depth reading for better accuracy.

**Comment by xhlinxm** [comment]
Thanks for your reply. I didn't see the lidar data in small scale data sequences. Maybe as you said, RGB - D camera offers depth reading for better accuracy.

**Comment by xhlinxm** [comment]
For small scale data sequences, is it possible to provide the point cloud of the corresponding scene (only the scene point cloud after mapping)?

**Comment by xhlinxm** [comment]
For small scale data sequences, is it possible to provide the point cloud of the corresponding scene (only the scene point cloud after mapping)?

**Comment by mgaoling** [comment]
Unfortunately, no for now. You can use a state-of-the-art algorithm to generate such scenes with ground truth poses.

**Comment by xhlinxm** [comment]
Thanks for your reply. As the point cloud generated by LiDAR mapping has the reflectivity of each point, it can provide more information when used. It would be better if small scale data sequences could provide an additional point cloud map. Anyway, thank you for your dataset and look forward to future updates.
