### ISSUE TITLE
Is it possible to provide high precision point cloud maps acquired by FARO？

### ISSUE THREAD

**Issue by xhlinxm** [mgaoling/mpl_dataset_toolbox#6]
Although SOTA's SLAM algorithm can be used to build a complete point cloud map, it may still not be perfect. As stated in the paper, the FARO laser is used to generate high-quality point clouds. Is it possible to provide high precision point cloud maps acquired by FARO？This can be used as a GT value for point cloud mapping. Thanks again for your work.

**Comment by mgaoling** [comment]
At this stage, we are not going to release the FARO map for all kinds of reasons. We will let you know once it is ready.

Meanwhile, it is suggested to build the complete point cloud map with some SOTA SLAM algorithms by feeding in the ground truth signals.

**Comment by xhlinxm** [comment]
Thank you
