### ISSUE TITLE
bag文件和动捕真值文件的起始时间戳对其问题

### ISSUE THREAD

**Issue by YoungHaulk** [mgaoling/mpl_dataset_toolbox#9]
作者您好，首先很感谢开源优秀的代码！
请教一个opticTrack采集真值问题。
我想用动捕采集相机的运动轨迹，同时录制bag文件，用于后续的定位精度对比。
动捕输出的真值，其时间戳是从0开始的，bag有准确的时间戳；因此，在对比精度时，需要将两者的时间戳对齐。
**请问怎么对齐两者的起始时间戳？**（如果取bag的起始时间戳作为两者的时间差，然后补偿到真值对应的时间戳上，这种方法前提是录制bag和真值是同一时刻开始的，这很难保证）

**Comment by mgaoling** [comment]
你好，感谢你的问题。针对你的需求，有以下三种可能的思路：

首先，可以不对齐两个时间序列。在每次采集数据时进行特定的动作，通过检测采集的运动峰值来对齐两个时间序列。这种方法简单易行，但是可能会对数据的精度产生一定的影响。

其次，可以在ROS层面实现软同步。具体而言是通过使用[VRPN](http://wiki.ros.org/vrpn_client_ros)来实现软同步。然而，这种方法可能会受到动捕系统的数据传输速度和网络延迟等因素的影响，导致两个时间序列不能完全精准对齐。

最后，可以实现动捕系统和相机系统的硬同步。具体可以参考这个[网页](https://star-datasets.github.io/vector/about/synchronization/)上的信息以及附带的开源同步工具箱。这种方法需要一定的硬件支持，但是可以实现较高的同步精度。
